services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - "C:/Users/newma/Desktop/fastapi-monitoring/fastapi.log:/var/log/fastapi.log"
    command: -config.file=/etc/promtail/config.yml
  tempo:
    image: grafana/tempo:2.5.0
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4317:4317"   # gRPC (OTLP)
      - "4318:4318"   # HTTP (OTLP)
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml